<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd">
	<xsd:element name="SMC_Applikationsart" type="OGD_Applikationsart"/>
	<xsd:complexType name="APPLIKATIONSART">
		<xsd:sequence>
			<xsd:element name="ZULASSUNGSNUMMER" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Zulassungsnummer</xsd:documentation>
					<xsd:documentation xml:lang="fr">Numéro d’autorisation</xsd:documentation>
					<xsd:documentation xml:lang="it">Numero di omologazione</xsd:documentation>
					<xsd:documentation xml:lang="en">Authorisation number</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="SEQUENZNUMMER" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Dosisstärke Nummer</xsd:documentation>
					<xsd:documentation xml:lang="fr">Numéro de dosage</xsd:documentation>
					<xsd:documentation xml:lang="it">Numero di dosaggio</xsd:documentation>
					<xsd:documentation xml:lang="en">Dosage strength number</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="APPLIKATIONSART_CODE" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Applikationsart</xsd:documentation>
					<xsd:documentation xml:lang="fr">Mode d’administration</xsd:documentation>
					<xsd:documentation xml:lang="it">Tipo di applicazione</xsd:documentation>
					<xsd:documentation xml:lang="en">Administration route</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="OGD_Applikationsart">
		<xsd:sequence>
			<xsd:element name="APPLIKATIONSART" minOccurs="0" maxOccurs="unbounded" type="APPLIKATIONSART"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
